server:
    port: 8082

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

spring:
    application:
        name: sms-service-api

management:
    endpoints:
        web:
            exposure:
                include: '*'
