server:
    port: 8082

eureka:
    client:
        service-url:
            defaultZone: http://eureka-service-registry:8761/eureka


spring:
    application:
        name: sms-service

management:
    endpoints:
        web:
            exposure:
                include: '*'
