version: "3"

services:
  loan-application-ui:
    image: "rhancav/loan-application-ui"
    container_name: loan-application-ui
    networks:
      - loan-application-network
    ports:
      - "9191:9191"
  findex-inquiry-service:
    image: "rhancav/findex-inquiry-service"
    container_name: findex-inquiry-service
    networks:
      - loan-application-network
    ports:
      - "8081:8081"
  api-gateway:
    image: "rhancav/api-gateway"
    container_name: api-gateway
    networks:
      - loan-application-network
    ports:
    - "9090:9090"
  eureka-service-registry:
    image: "rhancav/eureka-service-registry"
    container_name: eureka-service-registry
    networks:
      - loan-application-network
    ports:
    - "8761:8761"
  loan-application-service:
    image: "rhancav/loan-application-api"
    container_name: loan-application-service
    networks:
      - loan-application-network
    ports:
    - "8080:8080"
  sms-service:
    image: "rhancav/sms-service"
    container_name: sms-service
    networks:
      - loan-application-network
    ports:
    - "8082:8082"
networks:
  loan-application-network:

