version: "3"

services:
  eureka-service-registry:
    container_name: eureka-service-registry
    image: 'rhancav/eureka-service-registry:v1'
    networks:
      - loan-application-network
    ports:
      - "8761:8761"
    command: --spring.profiles.active=prod
  api-gateway:
    container_name: api-gateway
    image: 'rhancav/api-gateway:v1'
    networks:
      - loan-application-network
    ports:
      - "9090:9090"
    command: --spring.profiles.active=prod
  sms-service:
    container_name: sms-service
    image: 'rhancav/sms-service:v1'
    networks:
      - loan-application-network
    ports:
      - "8082:8082"
    command: --spring.profiles.active=prod
  findex-inquiry-service:
    container_name: findex-inquiry-service
    image: 'rhancav/findex-inquiry-service:v1'
    networks:
      - loan-application-network
    ports:
    - "8081:8081"
    command: --spring.profiles.active=prod
  loan-application-service:
    container_name: loan-application-service
    image: 'rhancav/loan-application-service:v1'
    networks:
      - loan-application-network
    ports:
    - "8080:8080"
    command: --spring.profiles.active=prod
  loan-application-ui:
    container_name: loan-application-ui
    image: 'rhancav/loan-application-ui:v1'
    networks:
      - loan-application-network
    ports:
    - "9191:9191"
    command: --spring.profiles.active=prod

networks:
  loan-application-network:
    driver: bridge
