server:
    port: 8081

eureka:
    client:
        service-url:
            defaultZone: http://eureka-service-registry:8761/eureka

spring:
    application:
        name: findex-inquiry-service
    profiles:
        active: prod
    datasource:
        driverClassName: org.h2.Driver
        password: test
        url: jdbc:h2:mem:consumer-db
        username: test
    h2:
        console:
            enabled: true
    jackson:
        serialization:
            indent_output: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        show-sql: false

management:
    endpoints:
        web:
            exposure:
                include: '*'

