server:
  port: 9191
spring:
  profiles:
    active: dev

loan:
  application:
    service:
      uri: http://localhost:9090/loan-application-service/api/loan-applications

findex:
  consumers:
    service:
      uri: http://localhost:9090/findex-inquiry-service/api/consumers
